server:
  port: 8076

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
spring:
    datasource:
        dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
        url: jdbc:mysql://10.5.113.86:3306/stockbook
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}
        connectionTimeout: 10000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false