server:
  port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-service 
          uri: lb://admin-service
          predicates:
          - Path=/api/user/**,/api/user/{id}/**,/api/users/**,/api/users/user/{id}/**,/api/users/user/{username}/**,/api/users/user/roles/{username}/**
        - id: utility-service 
          uri: lb://utility-service
          predicates:
          - Path=/api/utility/**
          filters:
          - RewritePath=/proxy/(?<api>.*), /$\{api} 
        - id: admin-service 
          uri: lb://admin-service
          predicates:
          - Path=/api/admin/**,/api/admin/update_activation_status/{id}/status/{status}/**          