server:
  port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-service 
          uri: lb://admin-service
          predicates:
          - Path=/api/user/**,/api/user/{id}/**,/api/users/**,/api/users/user/{id}/**,/api/users/user/{username}/**,/api/users/user/roles/{username}/**
        - id: product-service 
          uri: lb://product-service
          predicates:
          - Path=/api/product/**,/api/products/**,/api/category/**,/api/stock/**,/api/categories/**,/api/**
          filters:
          - RewritePath=/proxy/(?<api>.*), /$\{api}        